---
layout: post
title: "Upgrading to Jenkins 2.7.x LTS. Potential obstacles and solutions"
tags:
- lts
- jenkins2
author: oleg_nenashev
---

:toc:

NOTE: This is a post by link:https://github.com/oleg-nenashev[Oleg Nenashev], Jenkins contributor.
This post represents his *personal* opinion, which may differ from the official position of the Jenkins community.

=== Introduction

On July 6th, 2016 the community released the first Jenkins 2 *Long-Term Support (LTS)* version (_2.7.1_). 
On this week we also expect the 2.7.2 release.
*LTS* in Jenkins means a stabilization branch, 
which gets several bug fix releases over 12 weeks. 
Usage of such LTS versions is highly recommended for production Jenkins instances with high stability requirements.
You can read more about the LTS release and its maintenance policies link:https://wiki.jenkins-ci.org/display/JENKINS/LTS+Release+Line[here].

So many of you may consider updating to Jenkins 2.7.x LTS baseline.
As it stated in link:https://jenkins.io/blog/2016/07/07/jenkins-2/[Kohsuke's blogpost], _"the core of Jenkins is still the same, and all the plugins & existing configuration will just work"_.

I used to be a Jenkins administrator for many years, so my point of view is a bit different. 
In my opinion the update is *mostly safe*, 
but there are some changes, which may impact Jenkins environments.

In this blog post I would like to overview the changes between _1.651.x_ and _2.7.x_ LTS branches, which you may potentially experience during the upgrade.

=== What's inside Jenkins LTS 2.7.x?

Jenkins 2.7.x is a very first LTS version of link:https://jenkins.io/2.0/[Jenkins 2].
You can find the full list of changes by using
link:https://jenkins.io/changelog/[Jenkins Weekly changelogs] between your release and version _2.7_ *plus* 
changes in link:https://jenkins.io/changelog-stable/[Jenkins LTS changelog] for the _2.7.x_ LTS baseline.

I would like to mention several major changes for ones who upgrade from Jenkins _1.651.x_ LTS release. If you are interested in previous changes, you may need to perform some archeology.

==== Major new features and improvements
* Unbundling of plugins from the Jenkins core
* New Installation/Upgrade wizard, which allows installing various sets of plugins during the initial startup or upgrade
* Security hardening:
 ** New Jenkins installations start up in the locked mode
 ** link:https://wiki.jenkins-ci.org/display/JENKINS/CSRF+Protection[CSRF protection] is enabled by default on new installations
 ** link:https://wiki.jenkins-ci.org/display/JENKINS/Slave+To+Master+Access+Control[Slave to Master Access Control] is enabled by default on new installations
 ** JNLP3 protocol, which enables encryption between Jenkins master and agents. (link:https://issues.jenkins-ci.org/browse/JENKINS-26580[JENKINS-26580])

==== Major bugfixes

According to the changelogs, Jenkins _2.7.1_ contains more than *40* bugfixes compared to Jenkins _2.0_. 
Jenkins _2.7.2_ is about introducing *9* additional fixes.

Below you can find references to the most important ones:

* Correct support of the _no_proxy_ environment variable (link:https://issues.jenkins-ci.org/browse/JENKINS-32326)[JENKINS-32326)])
* Stability improvements in the communication layer between Jenkins master and agents 
(see the link:https://github.com/jenkinsci/remoting/blob/master/CHANGELOG.md[remoting changelogs])
* Jenkins didn't enable disabled dependencies during plugin installations (link:https://issues.jenkins-ci.org/browse/JENKINS-34494)[JENKINS-34494)])
* Secured Jenkins installations didn't properly save the queue on shutdown (link:https://issues.jenkins-ci.org/browse/JENKINS-34281[JENKINS-34281])
* etc.

According to the info above, Jenkins _2.7.x_ baseline is definitely useful from the stability point of view.

=== Obstacles when upgrading from previous LTS versions

In this section I would like to overview potential issues,
which may appear after the upgrade to the Jenkins 2 LTS.

==== Security-related obstacles

In Jenkins project we think that it is preferable to have a secured installation by default.
So the core frequently gets security fixes and enhancements.
Some of there fixes may impact the default behavior of Jenkins.

===== Security-by-default and configuration management tools

Jenkins _1.x_ used to start up in the unsecured mode.
It allowed to easily configure Jenkins instances on startup, 
but on the other hand an attacker was able to connect to the newly installed Jenkins
and to run/install a malicious code on the instance.

*Change*: Starting form Jenkins 2, the instance starts up in the locked mode. 
A Jenkins admin is able to unlock the instance by using a temporary password available within _JENKINS_HOME_.
Also, new Jenkins 2 instances start up with CSRF Protection and Slave-2-Master by default.

*Issue impact*: Security hardening impacted many configuration management tools, which used to presume that Jenkins starts up in the unsecured mode.

Examples of impacted tools:

* link:https://github.com/chef-cookbooks[chef-cookbooks/jenkins] (Issue link:https://github.com/chef-cookbooks/jenkins/issues/466[#466])
* link:https://github.com/jenkinsci/puppet-jenkins[puppet-jenkins] (Issue link:https://github.com/jenkinsci/puppet-jenkins/issues/575[#575])
* link:https://github.com/geerlingguy/ansible-role-jenkins/[geerlingguy/ansible-role-jenkins] (Issue link:https://github.com/geerlingguy/ansible-role-jenkins/issues/47[#47], fixed by link:https://github.com/karlmdavis/ansible-jenkins2[karlmdavis/ansible-jenkins2])
* link:https://python-jenkins.readthedocs.io[python-jenkins] (Issue link:https://bugs.launchpad.net/python-jenkins/+bug/1570408[#1570408])

If you use Configuration as Code for rolling up Jenkins instances, 
please be aware about this change.

*Recommended actions*: If you see the issue for your tools, please report them to tool maintainers.
If you manage configuration scripts on your own, consider using API and CLI via temporary "admin" user with credentials located in _JENKINS_HOME_.

===== SECURITY-170 follow-ups (pre 1.651.3 versions)

*SECURITY-170* is a major security fix, which has been introduced in Jenkins _1.651.3_ and _2.3_ versions.

The issue is related to the opportunity of passing build parameters, which have not been defined in job definitions.
Such behavior allows creating exploits for Jenkins by hijacking environment variables being used in scripts.
You can read more about this issue at the link:https://wiki.jenkins-ci.org/display/SECURITY/Jenkins+Security+Advisory+2016-05-11[Jenkins Security Advisory].

NOTE: *Lifehack*: 
Security fixes may alter the default behavior of Jenkins.
If you are aware about such issues, please subscribe to Jenkins Security Advisories.
See the guide link:https://wiki.jenkins-ci.org/display/JENKINS/Security+Advisories[here].

Many plugins were using such approach 
in order to pass data to build environments by variables without defining them in job properties.
And this 

*Issue impact*: 
At least *17 plugins* have been affected.
And bad news is that not all of them have been fixed by August 2016.
You can find the list of affected plugins and the current status on the link:https://wiki.jenkins-ci.org/display/JENKINS/Plugins+affected+by+fix+for+SECURITY-170[special Wiki page].

*Workaround*: Workarounds for Jenkins users and plugin developers are provided in the link:https://jenkins.io/blog/2016/05/11/security-update/[blogpost] by Daniel Beck.

==== Jenkins generic issues

===== Potential plugin compatibility issues

Jenkins 2 Upgrade Wizard offers installation of plugins,
which have not been bundled in previous Jenkins cores
(e.g. Git/GtHub stack, Folders, Pipeline).

In Jenkins project there are efforts in order to ensure compatibility of plugins,
but there are still risks when you update instances.
In the case of Jenkins Pipeline, there are still several known compatibility issues in plugins.

*Recommended actions*: On production instances it's highly recommended to test any plugin installations or upgrades.
If you experience any issue and cannot find a bug in Jenkins JIRA, please create a new one.

===== Change of Jenkins HTML layouts

In Jenkins 2 there was a significant effort related to improving of the WebUI user experience.
It lead to the change of layouts of several pages including configuration screens and the _New Item_ page.

*Impact*: HTML layout has changed. 
It impacts custom Web UI patches coming from custom JavaScript and CSS 
(as example, via link:https://wiki.jenkins-ci.org/display/JENKINS/Simple+Theme+Plugin[Simple Theme Plugin]). 

*Recommended actions*: You may have to update custom CSS and JavaScript files in order to make them compatible with the new layout.

===== Terminology changes may be confusing to users

In Jenkins 2 there was a renaming of "slaves" to "agents". 
You can see details about this update in
link:https://issues.jenkins-ci.org/browse/JENKINS-27268[JENKINS-27268].

*Impact*: Jenkins WebUI and documentation has been changed.
On the other hand, there are many plugins, which use Jenkins 1.x core as a baseline and follow its terminology.
If you have internal documentation, it may become outdated now 
(other Jenkins 2 changes also may require an update there).

*Recommended actions*: Custom documentation (text and screenshots) may need update.
If you see issues in plugins, create low-priority bugs to them. 
Likely it will take pretty much time to get updates everywhere.

=== Upgrade recommendations

After reading the info above you may think that upgrade to Jenkins _2.7.x_ may be dangerous.
And yes, I think that such upgrade may imply some risks for real-world Jenkins instances.

Does it mean that I do not recommend migrating to Jenkins 2?
The answer is *no*, actually I *recommend* using the latest Jenkins _2.7.x_ LTS version for new installations and for upgrading the previous ones.

It is not a secret that production system upgrade without testing is a bad practice.
And no wonder the rule also applies to automation servers like Jenkins.
If you perform upgrade, it's highly recommended to evaluate the upgrade on a test server before pushing changes to production.
Or to have a backup at least...

If you consider upgrading now, I would recommend the following approach:

0. Perform backup of your system (or use a test instance)
0. Install Jenkins _2.7.2_ LTS to your system
0. When Jenkins starts up, run the _Upgrade Wizard_ and select plugins to be installed
0. Upgrade plugins, especially ones mentioned in 
link:https://wiki.jenkins-ci.org/display/JENKINS/Plugins+affected+by+fix+for+SECURITY-170[SECURITY-170 impact list]
and link:https://wiki.jenkins-ci.org/display/SECURITY/Jenkins+Security+Advisory+2016-06-20[2016-06-20 Security Advisory for plugins]
0. If you still have plugins affected by *SECURITY-170*, consider link:https://jenkins.io/blog/2016/05/11/security-update/[applying a workaround] (*warning*: the workaround may impact security of your instance)
0. After the system startup, consider enabling CSRF protection and Slave-2-Master security feature if they were disabled on your previous setup.
0. Test your Jenkins instance and other services using its CLI and REST API. Fix the 
0. Make decisions regarding further steps:
 * If the instance works fine, you may keep the upgrade (or upgrade the production instance)
 * If you hit a showstopper, let Jenkins community know about it by 
link:https://wiki.jenkins-ci.org/display/JENKINS/How+to+report+an+issue[creating an issue] and then restore the system from backup.
0. After the upgrade, update your internal documentation in order to reflect changes in the WebUI and "slave/agent" terminology.

=== Conclusions

I think that Jenkins 27.x LTS releases provide much important changes including security fixes.
Jenkins installations may definitely benefit from upgrading to this release.

Hopefully this guide will help you to create a proper upgrade plan and to avoid the mentioned obstacles.
If you discover something new, please do not hesitate to contact Jenkins core team using  
link:https://issues.jenkins-ci.org[JIRA bugtracker] or other channels.
